### ISSUE TITLE
Gazebo topic remap

### ISSUE THREAD

**Issue by fbenti** [gazebosim/ros_gz#392]
Hello, I was wondering if it is possible to remap a gazebo topic to a different name. 

So basically, I'm spawning a model with a camera, which publish on a topic `/camera`. Is it possible to remap it to `/camera_1` at runtime or it could be done only beforehand?

**Comment by azeey** [comment]
You can remap topics using ROS once you've created a bridge, but topic remapping is not currently supported directly on Gazebo (gz-transport) topics. If you are requesting that as a feature, the issue should go into the gz-transport repo.

**Comment by caguero** [comment]
Gazebo topics can only be remapped programmatically. See this tutorial https://gazebosim.org/api/transport/12/messages.html in case that's useful. Otherwise, do it at the ROS level as @azeey recommended.

**Comment by oscar-lima** [comment]
If what you want is for a topic to have a different name under ros2, you can do something like:

```yaml
- gz_topic_name: joint_states
  gz_type_name: gz.msgs.Model
  ros_topic_name: mir_joint_states
  ros_type_name: sensor_msgs/msg/JointState
  direction: GZ_TO_ROS
```

instead of:

```yaml
- topic_name: joint_states
  ros_type_name: sensor_msgs/msg/JointState
  gz_type_name: gz.msgs.Model
  direction: GZ_TO_ROS
```

In your bridge config file, this gives you more control over the names but is not a remapping within Gazebo, just ros2 "sees" a different name.
